# Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: 192.168.137.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

# Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: manu@gmail.com
EMAIL_PASSWORD:

VERIFY_EMAIL_HOST: http://localhost:8085
